version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: dockerfile
        container_name: nestjs-app
        restart: unless-stopped
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - APP_NAME=${APP_NAME}

            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}

            - MONGO_DB=${MONGO_DB}
            - MONGO_USERNAME=${MONGO_USERNAME}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - MONGO_HOST=${MONGO_HOST}
            - MONGO_PORT=${MONGO_PORT}

            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}

            - JWT_SECRET=${JWT_SECRET}
            - TWO_FACTOR_SECRET_KEY=${TWO_FACTOR_SECRET_KEY}
            - PEPPER_SECRET=${PEPPER_SECRET}
            - LOG_LEVEL=info
        depends_on:
            - postgree
            - redis
            - mongoDB
        networks:
            - app-network
        # deploy:
        #     resources:
        #         limits:
        #             cpu: '1'
        #             memory: 512M
        #         reservation:
        #             cpus: '0.5'
        #             memory: 256M

    postgree:
        image: postgres:latest
        container_name: postgree
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '${POSTGRES_PORT}:5432'
        networks:
            - app-network
        # healthcheck:
        #     test: ["CMD-SHELL", "pg_isready -U postgres"]
        #     interval: 10s
        #     timeout: 5s
        #     retries: 5

    mongoDB:
        image: mongo:latest
        container_name: mongoDB
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
        ports:
            - '27017:27017'
        networks:
            - app-network

    redis:
        image: redis:7-alpine
        container_name: redis
        ports:
            - '${REDIS_PORT}:6379'
        networks:
            - app-network

# volumes:
#     postgres_data:

networks:
    app-network:
        driver: bridge
